/* tslint:disable */
/* eslint-disable */
/**
 * ShaFuku API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddUserDto
 */
export interface AddUserDto {
    /**
     * 
     * @type {number}
     * @memberof AddUserDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AddUserDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AddUserDto
     */
    loginId?: string;
    /**
     * 
     * @type {string}
     * @memberof AddUserDto
     */
    createdAt?: string;
    /**
     * 
     * @type {number}
     * @memberof AddUserDto
     */
    createUserId?: number;
    /**
     * 
     * @type {string}
     * @memberof AddUserDto
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof AddUserDto
     */
    updateUserId?: number;
    /**
     * 
     * @type {string}
     * @memberof AddUserDto
     */
    password: string;
}

export function AddUserDtoFromJSON(json: any): AddUserDto {
    return AddUserDtoFromJSONTyped(json, false);
}

export function AddUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUserDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'loginId': !exists(json, 'loginId') ? undefined : json['loginId'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'createUserId': !exists(json, 'createUserId') ? undefined : json['createUserId'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'updateUserId': !exists(json, 'updateUserId') ? undefined : json['updateUserId'],
        'password': json['password'],
    };
}

export function AddUserDtoToJSON(value?: AddUserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'loginId': value.loginId,
        'createdAt': value.createdAt,
        'createUserId': value.createUserId,
        'updatedAt': value.updatedAt,
        'updateUserId': value.updateUserId,
        'password': value.password,
    };
}

